"""Add is_admin to User model

Revision ID: 4a7180634467
Revises: 4a29befe6701
Create Date: 2024-07-24 12:08:34.853061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7180634467'
down_revision = '4a29befe6701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_event_organization_id', 'organization', ['organization_id'], ['id'])  # Added constraint name

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_organization_id', type_='foreignkey')  # Added constraint name
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
